use_frameworks!

platform :ios, '8.0'

target 'LWAudioPlayer_Example' do
  pod 'LWAudioPlayer', :path => '../'

  pod 'Masonry','1.1.0'

  target 'LWAudioPlayer_Tests' do
    inherit! :search_paths
  end
end
